site_name: CiviCRM Mediwe Basis
repo_url: https://github.com/CiviCooP/be.mediwe.basis
theme: material

pages:
- Home: index.md
- Configuratie items voor CiviCRM: configitems.md
- Tekst fragmenten: tekst_fragmenten.md
- Contact Types: contacttypes.md
- Dossier Type Ziektemelding: ziektemelding.md
- Dossier Type Medische Controle: medische_controle.md
- Email naar de controlearts: bericht_arts.md
- Email dat een resultaat binnenkwam met de app: resultaat_app.md
- Bevestigingsmail naar de klant: bevestiging_klant.md
- Andere mailberichten naar de klant: andere_mails_klant.md
- SMS berichten naar medewerkers: sms_medewerker.md
- Dagelijkse mail voor app gebruikers: app_link_mail.md
- Drupal modules (en themes): drupalmodules.md
- CiviCRM extensies: civiextensions.md
- Automatische Acties: automatische_acties.md
- Documentatie bijwerken: documentatie.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc(permalink=true)
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark